all: server-block client server-et

server-block: server-block.cpp
	g++ -o server-block server-block.cpp

server-et: server-et.cpp
	g++ -o server-et server-et.cpp

client: client.cpp
	g++ -o client client.cpp

clean: 
	rm client server-block server-et